# Main part
sudo: required
services:
  - docker

# Pre install part
before_install:
  - docker build -t mroldsir/docker-react -f Dockerfile.dev .

# Script part
script:
  - docker run mroldsir/docker-react npm run test -- --coverage

# Deploy part
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-1-086727439383"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
